server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

outbound:
  identity:
    client-id: ${client_id}
    client-secret: ${client_secret}
    redirect-uri: ${re_direct_google}

cloudinary:
  cloud_name: ${cloud_name}
  api_key: ${api_key}
  api_secret: ${api_secret}

jwt:
  signerKey: ${signerKey}
  valid-duration: 36000 # in second
  refreshable-duration: 36000 # in seconds

payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    returnUrl: "http://localhost:3000/vn-pay-callback"
    tmnCode: ${tmnCode}
    secretKey: ${secret_key}
    version: "2.1.0"
    command: "pay"
    orderType: "other"
redis:
  redisPort: 6379
  redisHost: ${redis_host}
email:
  email_key: ${email_key}
